name: "OpenClaw"
description: "Personal AI assistant gateway"
version: "2.0.2"
slug: "openclaw"
image: "ghcr.io/seofood/openclaw"
arch:
  - amd64
host_network: true
init: false
hassio_api: true
map:
  - share:rw
options:
  port: 18789
schema:
  port: int
